---
driver:
  name: docker
  hostname: helm.kitchen.local
  use_sudo: false

platforms:
  - name: ubuntu-xenial
    driver_config:
      image: 'trevorj/salty-whales:xenial'
      platform: ubuntu

provisioner:
  name: salt_solo
  log_level: info
  require_chef: false
  salt_version: latest
  formula: helm
  state_top:
    base:
      '*':
        - helm

verifier:
  name: inspec

suites:
  - name: defaults
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - helm
        helm.sls:
          helm:
            tiller:
              install: false
  - name: helm
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - helm
        helm.sls:
          helm:
            bin: /usr/local/bin/helm
            helm_home: /root/.helm
            tiller:
              install: false
            kubectl:
              manage_config: true
              config_file: /srv/helm/kubeconfig.yml
              config:
                cluster: 
                  server: https://kubernetes.example.com
                  certificate-authority-data: base64_of_ca_certificate
                cluster_name: kubernetes.example
                context_name: kubernetes-example
                user:
                  username: admin
                  password: uberadminpass
                user_name: admin
            repos:
              incubator: https://kubernetes-charts-incubator.storage.googleapis.com/